services:
  dozzle:
    image: amir20/dozzle:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "9999:8080"
    restart: unless-stopped

  base-python-dev:
    build:
      context: ./base-python-dev
    image: base-python-dev:latest
    ports:
      - "8888:8888"

  ml-workspace:
    build:
      context: ./ml-workspace
    image: ml-workspace:latest
    ports:
      - "8888:8888"

  dl-workspace-cpu:
    build:
      context: ./dl-workspace-cpu
    image: dl-workspace-cpu:latest
    ports:
      - "8888:8888"

  dl-workspace-gpu:
    build:
      context: ./dl-workspace-gpu
    image: dl-workspace-gpu:latest
    ports:
      - "8888:8888"

  llm-workspace:
    build:
      context: ./llm-workspace
    image: llm-workspace:latest
    ports:
      - "8888:8888"
